modLoader="javafml"
loaderVersion="[47,)"

license="${mod_license}"

[[mods]] #mandatory
# The modid of the mod
modId="createdungeons" #mandatory
# The version number of the mod
version="[1.0.0)"
displayName="Create Dungeons" #mandatory

authors="Halocovenet7" #optional


description='''${mod_description}'''
[[dependencies.createdungeons]] #optional
    modId="forge" #mandatory
    mandatory=true #mandatory
versionRange="[47.1.43,)"
    ordering="NONE"
    side="BOTH"
# Here's another dependency
[[dependencies.createdungeons]]
    modId="minecraft"
    mandatory=true
    versionRange="1.20,1.20.1"
    ordering="NONE"
    side="BOTH"

[[dependencies.createdungeons]]
modId="create"
mandatory=true
versionRange="[0.5.1.f,)"
ordering="NONE"
side="BOTH"


[[dependencies.createdungeons]]
modId="flywheel"
mandatory=true
versionRange="[0.6.10,0.6.11)"
ordering="AFTER"
side="CLIENT"